export const blogData =  {
"cat" : "The cat (Felis catus) is a domestic species of small carnivorous mammal.It is the only domesticated species in the family Felidae and is commonly referred to as the domestic cat or house cat to distinguish it from the wild members of the family.[4] Cats are commonly kept as house pets but  can also be farm cats or feral cats; the feral cat ranges freely and avoids  human contact.[5] Domestic cats are valued by humans for companionship and their ability to kill vermin. About 60 cat breeds are recognized by various cat registries.[6]",

"dolphin" :   "A dolphin is an aquatic mammal within the infraorder Cetacea. Dolphin species belong to the families  Delphinidae (the oceanic dolphins), Platanistidae (the Indian river dolphins), Iniidae (the New World  river dolphins), Pontoporiidae (the brackish dolphins), and possibly extinct Lipotidae (baiji or  Chinese river dolphin). There are 40 extant species named as dolphins.",

"octopus" : "An octopus (pl: octopuses or octopodes[a]) is a soft-bodied, eight-limbed mollusc of the order  Octopoda (/ɒktɒpədə/, ok-TOP-ə-də[3]). The order consists of some 300 species and is grouped  within the class Cephalopoda with squids, cuttlefish, and nautiloids. Like other cephalopods, an  octopus is bilaterally symmetric with two eyes and a beaked mouth at the center point of the eight  limbs.[b] The soft body can radically alter its shape, enabling octopuses to squeeze through small  gaps.",

"whale" : "The blue whale (Balaenoptera musculus) is a marine mammal and a baleen whale. Reaching a maximum  confirmed length of 29.9 meters (98 ft) and weighing up to 199 tonnes (196 long tons; 219 short  tons), it is the largest animal known ever to have existed.[a] The blue whale's long and slender  body can be of various shades of greyish-blue dorsally and somewhat lighter underneath.",

"giraffe" : "The giraffe is a large African hoofed mammal belonging to the genus Giraffa. It is the tallest living terrestrial animal and the largest ruminant on Earth. Traditionally, giraffes were thought to be one species, Giraffa camelopardalis, with nine subspecies. Most recently, researchers proposed dividing them into up to eight extant species due to new research into their mitochondrial and nuclear DNA, as well as morphological measurements. Seven other extinct species of Giraffa are known from the fossil record.",

"dog" : "The dog (Canis familiaris[4][5] or Canis lupus familiaris[5]) is a domesticated descendant of the wolf. Also called the domestic dog, it is derived from extinct Pleistocene wolves,[6][7] and the modern wolf is the dog's nearest living relative.[8] Dogs were the first species to be domesticated[9][8] by hunter-gatherers over 15,000 years ago[7] before the development of agriculture.[1] Due to their long association with humans, dogs have expanded to a large number of domestic individuals[10] and gained the ability to thrive on a starch-rich diet that would be inadequate for other canids.[11]",

"parrot" : "Parrots, also known as psittacines (/ˈsɪtəsaɪnz/),[1][2] are birds of the order Psittaciformes (/ˈsɪtəsɪfɔːrmiːz/) and are found mostly in tropical and subtropical regions. They are made up of four families that contain roughly 410 species in 101 genera. The four families are: Psittaculidae (Old World parrots) , the Psittacidae (African and New World parrots), the Cacatuoidea (cockatoos), and the Strigopidae (New Zealand parrots). One-third of all parrot species are threatened by extinction, with higher aggregate extinction risk (IUCN Red List Index) than any other comparable bird group.[3] Parrots have a generally pantropical distribution with several species inhabiting temperate regions in the Southern Hemisphere, as well. The greatest diversity of parrots is in South America[4] and Australasia.",

"crow" : "Crows form the genus Corvus in the family Corvidae. They are medium to large sized birds, carnivores and scavengers.\n\nThe genus includes the crow (carrion crow or hooded crow), the rook, jackdaw, and the large common raven. The genus has 40 or so members on all temperate continents except for South America, and some islands.\n\nThe Corvus makes up a third of the species in the Corvidae. Crows appear to have evolved in Asia from corvid stock which had evolved in Australia. The collective name for a group of crows is a flock or, more poetically, a murder.[1]",

"sparrow" : "The house sparrow (Passer domesticus) is a bird of the sparrow family Passeridae, found in most parts of the world. It is a small bird that has a typical length of 16 cm (6.3 in) and a mass of 24–39.5 g (0.85–1.39 oz). Females and young birds are coloured pale brown and grey, and males have brighter black, white, and brown markings. One of about 25 species in the genus Passer, the house sparrow is native to most of Europe, the Mediterranean Basin, and a large part of Asia. Its intentional or accidental introductions to many regions, including parts of Australasia, Africa, and the Americas, make it the most widely distributed wild bird.",

"magnolia" : "Magnolia is a large genus of about 210 to 340[a] flowering plant species in the subfamily Magnolioideae of the family Magnoliaceae. It is named after the French botanist Pierre Magnol.Magnolia is an ancient genus. Appearing before bees evolved, the flowers are theorized to have evolved to encourage pollination by beetles.[2] To avoid damage from pollinating beetles, the carpels of Magnolia flowers are extremely tough.[3] Fossilized specimens of M. \nacuminata have been found dating to 20 million years ago, and fossils of plants identifiably belonging to the Magnoliaceae date to 95 million years ago.",

"jasmine" : "Jasmine (taxonomic name: Jasminum; /ˈjæsmɪnəm/, YASS-min-əm[5]) is a genus of shrubs and vines in the olive family of Oleaceae.[4][6][7]: 193  It contains around 200 species native to tropical and warm temperate regions of Eurasia, Africa, and Oceania.[7]: 194  Jasmines are widely cultivated for the characteristic fragrance of their flowers. A number of unrelated plants contain the word jasmine in their common names (see Other plants called jasmine).",

"willow" : "Willows, also called sallows and osiers, of the genus Salix, comprise around 350 species (plus numerous hybrids) of typically deciduous trees and shrubs, found primarily on moist soils in cold and temperate regions. \n\nMost species are known as willow, but some narrow-leaved shrub species are called osier, and some broader-leaved species are referred to as sallow (from Old English sealh, related to the Latin word salix, willow). \n\nSome willows (particularly arctic and alpine species) are low-growing or creeping shrubs; for example, the dwarf willow (Salix herbacea) rarely exceeds 6 centimetres (2+1⁄2 in) in height, though it spreads widely across the ground.",

"coconut" : "The coconut tree (Cocos nucifera) is a member of the palm tree family (Arecaceae) and the only living species of the genus Cocos.[1] The term coconut (or the archaic cocoanut)[2] can refer to the whole coconut palm, the seed, or the fruit, which botanically is a drupe, not a nut. The name comes from the old Portuguese word coco, meaning head or skull, after the three indentations on the coconut shell that resemble facial features. They are ubiquitous in coastal tropical regions and are a cultural icon of the tropics.",

"banyan" : "Ficus benghalensis, commonly known as the banyan, banyan fig and Indian banyan,[2] is a tree native to the Indian Subcontinent. Specimens in India are among the largest trees in the world by canopy coverage. It is also known as the strangler fig because it starts out as epiphyte, that is, leaning on another tree that it ends up suffocating.",

"neem" : "Azadirachta indica, commonly known as margosa, neem, nimtree or Indian lilac,[3] is a tree in the mahogany family Meliaceae. It is one of two species in the genus Azadirachta. It is native to the northeast of the Indian subcontinent and to Indochina, but is naturalized and grown around the world in tropical and subtropical areas. Its fruits and seeds are the source of neem oil. Nīm (नीम/نیم) is a Hindustani noun derived from Sanskrit nimba (निंब).[4][5][6]",

"oleander" : "Nerium oleander (/ˈnɪəriəm ... / NEER-ee-əm),[2] most commonly known as oleander or nerium, is a shrub or small tree cultivated worldwide in temperate and subtropical areas as an ornamental and landscaping plant. It is the only species currently classified in the genus Nerium, belonging to subfamily Apocynoideae of the dogbane family Apocynaceae. It is so widely cultivated that no precise region of origin has been identified, though it is usually associated with the Mediterranean Basin.",

"pistachio" : "The pistachio (/pɪˈstɑːʃioʊ, -ˈstæʃ-/ pist-A(H)SH-ee-oh;[2] Pistacia vera), a member of the cashew family, is a small tree originating from an area that includes Afghanistan, Central Asia, and Iran. The tree produces seeds that are widely consumed as food.\n\nThe pistachio tree is native to regions of Central Asia, including present-day Iran and Afghanistan.[4][5][6][7] Archaeology shows that pistachio seeds were a common food as early as 6750 BCE.[8] The earliest evidence of pistachio consumption goes back to the Bronze Age Central Asia and comes from Djarkutan, modern Uzbekistan.[9][10]",

"aloe-vera" : "Aloe vera (/ˈæloʊ(i) vɛrə, vɪər-/)[3] is a succulent plant species of the genus Aloe.[4] It is widely distributed, and is considered an invasive species in many world regions.[4][5] \n\nAn evergreen perennial, it originates from the Arabian Peninsula, but grows wild in tropical, semi-tropical, and arid climates around the world.[4] It is cultivated for commercial products, mainly as a topical treatment used over centuries.[4][5] The species is attractive for decorative purposes, and succeeds indoors as a potted plant.[6]",

"airplane" : "An airplane (American English), or aeroplane (Commonwealth English), informally plane, is a fixed-wing aircraft that is propelled forward by thrust from a jet engine, propeller, or rocket engine. Airplanes come in a variety of sizes, shapes, and wing configurations. The broad spectrum of uses for airplanes includes recreation, transportation of goods and people, military, and research. Worldwide, commercial aviation transports more than four billion passengers annually on airliners[1] and transports more than 200 billion tonne-kilometers[2] of cargo annually, which is less than 1% of the world's cargo movement.[3] Most airplanes are flown by a pilot on board the aircraft, but some are designed to be remotely or computer-controlled such as drones.",

"helicopter" : "A helicopter is a type of rotorcraft in which lift and thrust are supplied by horizontally spinning rotors. This allows the helicopter to take off and land vertically, to hover, and to fly forward, backward and laterally. These attributes allow helicopters to be used in congested or isolated areas where fixed-wing aircraft and many forms of short take-off and landing (STOL) or short take-off and vertical landing (STOVL) aircraft cannot perform without a runway.",

"hot-air-balloon" : "A hot air balloon is a lighter-than-air aircraft consisting of a bag, called an envelope, which contains heated air. Suspended beneath is a gondola or wicker basket (in some long-distance or high-altitude balloons, a capsule), which carries passengers and a source of heat, in most cases an open flame caused by burning liquid propane. The heated air inside the envelope makes it buoyant, since it has a lower density than the colder air outside the envelope. As with all aircraft, hot air balloons cannot fly beyond the atmosphere. The envelope does not have to be sealed at the bottom, since the air inside the envelope is at about the same pressure as the surrounding air.",

"car" : "A car, or an automobile is a motor vehicle with wheels. Most definitions of cars say that they run primarily on roads, seat one to eight people, have four wheels, and mainly transport people, not cargo.[1][2]French inventor Nicolas-Joseph Cugnot built the first steam-powered road vehicle in 1769, while French-born-Swiss inventor François Isaac de Rivaz designed and constructed the first internal combustion powered automobile in 1808. The modern car—a practical, marketable automobile for everyday use—was invented in 1886, when German inventor Carl Benz patented his Benz Patent-Motorwagen. Commercial cars became widely available during the 20th century. One of the first cars affordable by the masses was the 1908 Model T, an American car manufactured by the Ford Motor Company.",

"motorcycle" : "A motorcycle (motorbike, bike, or trike (if three-wheeled)) is a two or three-wheeled motor vehicle steered by a handlebar from a saddle-style seat.[1][2][3]\n\nMotorcycle design varies greatly to suit a range of different purposes: long-distance travel, commuting, cruising, sport (including racing), and off-road riding. Motorcycling is riding a motorcycle and being involved in other related social activities such as joining a motorcycle club and attending motorcycle rallies.\n\nThe 1885 Daimler Reitwagen made by Gottlieb Daimler and Wilhelm Maybach in Germany was the first internal combustion, petroleum-fueled motorcycle. In 1894, Hildebrand & Wolfmüller became the first series production motorcycle.[4][5]",

"bicycle" : "A bicycle, also called a pedal cycle, bike, push-bike or cycle, is a human-powered or motor-powered assisted, pedal-driven, single-track vehicle, having two wheels attached to a frame, one behind the other. A bicycle rider is called a cyclist, or bicyclist. \n\nBicycles were introduced in the 19th century in Europe. By the early 21st century there were more than 1 billion.[1][2][3] These numbers far exceed the number of cars, both in total and ranked by the number of individual models produced.[4][5][6] They are the principal means of transportation in many regions. They also provide a popular form of recreation, and have been adapted for use as children's toys, general fitness, military and police applications, courier services, bicycle racing, and bicycle stunts.",

"ship" : "A ship is a large watercraft that travels the world's oceans and other sufficiently deep waterways, carrying cargo or passengers, or in support of specialized missions, such as defense, research and fishing. Ships are generally distinguished from boats, based on size, shape, load capacity and purpose. Ships have supported exploration, trade, warfare, migration, colonization, and science. Ship transport is responsible for the largest portion of world commerce. \n\nThe word ship has meant, depending on the era and the context, either just a large vessel or specifically a ship-rigged sailing ship with three or more masts, each of which is square-rigged.",

"boat" : "A boat is a watercraft of a large range of types and sizes, but generally smaller than a ship, which is distinguished by its larger size, shape, cargo or passenger capacity, or its ability to carry boats. \n\nSmall boats are typically found on inland waterways such as rivers and lakes, or in protected coastal areas. However, some boats, such as the whaleboat, were intended for use in an offshore environment. In modern naval terms, a boat is a vessel small enough to be carried aboard a ship.[1] \n\nBoats vary in proportion and construction methods with their intended purpose, available materials, or local traditions. Canoes have been used since prehistoric times and remain in use throughout the world for transportation, fishing, and sport.",

"submarine" : "A submarine (or sub) is a watercraft capable of independent operation underwater. It differs from a submersible, which has more limited underwater capability.[1] The term is also sometimes used historically or colloquially to refer to remotely operated vehicles and robots, as well as medium-sized or smaller vessels, such as the midget submarine and the wet sub. Submarines are referred to as boats rather than ships irrespective of their size.[2] \n\nAlthough experimental submarines had been built earlier, submarine design took off during the 19th century, and they were adopted by several navies.",

"html" : "The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser. It defines the meaning and structure of web content. It is often assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScript.", 

"css" : "Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language such as HTML or XML (including XML dialects such as SVG, MathML or XHTML).[1] CSS is a cornerstone technology of the World Wide Web, alongside HTML and JavaScript.[2]\n\nCSS is designed to enable the separation of content and presentation, including layout, colors, and fonts.[3] This separation can improve content accessibility; provide more flexibility and control in the specification of presentation characteristics; enable multiple web pages to share formatting by specifying the relevant CSS in a separate .css file, which reduces complexity and repetition in the structural content; and enable the .css file to be cached to improve the page load speed between the pages that share the file and its formatting.", 

"javascript" : "JavaScript (/ˈdʒɑːvəskrɪpt/), often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2023, 98.7% of websites use JavaScript on the client side for webpage behavior,[10] often incorporating third-party libraries. All major web browsers have a dedicated JavaScript engine to execute the code on users' devices.\n\nJavaScript is a high-level, often just-in-time compiled language that conforms to the ECMAScript standard.[11] It has dynamic typing, prototype-based object-orientation, and first-class functions. It is multi-paradigm, supporting event-driven, functional, and imperative programming styles. It has application programming interfaces (APIs) for working with text, dates, regular expressions, standard data structures, and the Document Object Model (DOM).", 

"nodejs" : "Node.js is a cross-platform, open-source server environment that can run on Windows, Linux, Unix, macOS, and more. Node.js is a back-end JavaScript runtime environment, runs on the V8 JavaScript engine, and executes JavaScript code outside a web browser.\n\node.js lets developers use JavaScript to write command line tools and for server-side scripting. The ability to run JavaScript code on the server is often used to generate dynamic web page content before the page is sent to the users web browser. Consequently, Node.js represents a JavaScript everywhere paradigm,[6] unifying web-application development around a single programming language, as opposed to using different languages for the server- versus client-side programming.", 

"express.js" : "Express.js, or simply Express, is a back end web application framework for building RESTful APIs with Node.js, released as free and open-source software under the MIT License. It is designed for building web applications and APIs.[3] It has been called the de facto standard server framework for Node.js.[4]\n\nThe original author, TJ Holowaychuk, described it as a Sinatra-inspired server,[5] meaning that it is relatively minimal with many features available as plugins. Express is the back-end component of popular development stacks like the MEAN, MERN or MEVN stack, together with the MongoDB database software and a JavaScript front-end framework or library.[6]", 

"nest.js" : "Nest is a framework for building efficient, scalable Node.js server-side applications. It uses modern JavaScript, is built with TypeScript (preserves compatibility with pure JavaScript) and combines elements of OOP (Object Oriented Programming), FP (Functional Programming), and FRP (Functional Reactive Programming).\n\nUnder the hood, Nest makes use of Express, but also, provides compatibility with a wide range of other libraries, like e.g. Fastify, allowing for easy use of the myriad third-party plugins which are available.", 

"mongodb" : "MongoDB is a source-available cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas. MongoDB is developed by MongoDB Inc. and current versions are licensed under the Server Side Public License (SSPL) which is considered non-free by some organizations and distributions. MongoDB is a member of the MACH Alliance.", 

"vscode" : "Visual Studio Code, also commonly referred to as VS Code,[9] is a source-code editor made by Microsoft with the Electron Framework, for Windows, Linux and macOS.[10] Features include support for debugging, syntax highlighting, intelligent code completion, snippets, code refactoring, and embedded Git. Users can change the theme, keyboard shortcuts, preferences, and install extensions that add functionality.\n\nIn the Stack Overflow 2023 Developer Survey, Visual Studio Code was ranked the most popular developer environment tool among 86,544 respondents, with 73.71% reporting that they use it. It increased its use among those learning to code versus those developing as a profession (78% vs. 74%).[11]", 

"github" : "GitHub, Inc. (/ˈɡɪthʌb/[a]) is a platform and cloud-based service for software development and version control using Git, allowing developers to store and manage their code. It provides the distributed version control of Git plus access control, bug tracking, software feature requests, task management, continuous integration, and wikis for every project.[6] Headquartered in California, it has been a subsidiary of Microsoft since 2018.[7]\n\nIt is commonly used to host open source software development projects.[8] As of January 2023, GitHub reported having over 100 million developers[9] and more than 372 million repositories,[10] including at least 28 million public repositories.[11] It is the largest source code host as of June 2023."
}